#ifndef EVE_CONFIG_H
#define EVE_CONFIG_H

#define MIN_FOOD_SIZE 5.0
#define MAX_FOOD_SIZE 20.0
#define SURVIVAL_THRESHOLD MAX_FOOD_SIZE

/* DEBUG CONSTANTS */
#define RENDER_TERMINALVIEW false

#endif //EVE_CONFIG_H
