#ifndef EVE_CONFIG_H
#define EVE_CONFIG_H

#define MIN_FOOD_SIZE 5.0
#define MAX_FOOD_SIZE 20.0
#define SURVIVAL_THRESHOLD MAX_FOOD_SIZE
#define VISION_RANGE 10.0

/* DEBUG CONSTANTS */
#define RENDER_TERMINALVIEW false

#define AMOUNT_OF_FREDS 0
#define AMOUNT_OF_PIERCIES 1

#endif //EVE_CONFIG_H
